---

  - name: Ensure SickBeard service group exists
    group:
      name: "{{ sickbeard_group_name }}"
      gid: "{{ sickbeard_group_gid }}"
      system: true
      state: present
           
  - name: Ensure SickBeard service user exists
    user:
      name: "{{ sickbeard_user_name }}"
      uid: "{{ sickbeard_user_uid }}"
      group: "{{ sickbeard_group_name }}"
      home: "{{ sickbeard_user_home }}"
      system: true
      state: present

  - name: Ensure SickBeard dependencies are installed
    package: name={{ sickbeard_dependencies }} state=present

  - name: Ensure SickBeard library directory exists
    file:
      dest: "{{ sickbeard_library_path }}"
      owner: "{{ sickbeard_user_name }}"
      group: "{{ sickbeard_group_name }}"
      state: directory

  - name: Ensure SickBeard config directory exists
    file:
      dest: "{{ sickbeard_conf_path }}"
      owner: "{{ sickbeard_user_name }}"
      group: "{{ sickbeard_group_name }}"
      recurse: true
      state: directory

  - name: Fetch SickBeard source code
    git:
      repo: "{{ sickbeard_clone_uri }}"
      dest: "{{ sickbeard_user_home }}/src"
      update: false
      accept_hostkey: true
    become: true
    become_user: "{{ sickbeard_user_name }}"

  - name: Deploy SickBeard service manifest
    template:
      src: "{{ sickbeard_service_file.src }}"
      dest: "{{ sickbeard_service_file.dest }}"
      owner: root
      group: root
      mode: 0600
    notify:
      - Reload Sickbeard service config
      - Restart Sickbeard service

  - meta: flush_handlers

  - name: Ensure SickBeard service is running and enabled on boot
    service: name=sickbeard state=started enabled=yes
